# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

# Pre-install packages for the ubuntu distribution
cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/skvideo_build_ubuntu
  - $HOME/.cache/pip
  - $HOME/download
addons:
  apt:
    packages:
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
      - python-numpy
      - ffmpeg
      - mediainfo
      - g++-4.9

env:
  matrix:
    # This environment tests that scikit-learn can be built against
    # versions of numpy, scipy with ATLAS that comes with Ubuntu Precise 12.04
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7" COVERAGE="true"
      CYTHON_VERSION="0.23.4" NAME="ubuntu"
before_install:
    # Build ffmpeg (the real ffmpeg, not libav)
  - wget --no-check-certificate http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 || exit 1
  - tar xjf ffmpeg-snapshot.tar.bz2
  - cd ffmpeg
  - echo ./configure
  - mkdir ~/ffmpeg_install 
  - echo ./configure
  - ./configure --disable-yasm --disable-static --enable-shared --disable-doc --prefix="~/ffmpeg_install" || exit 2
  - echo make
  - make -j4 || exit 3
  - echo make install
  - make install || exit 4
  - cd ..

install: source continuous_integration/install.sh
script: bash continuous_integration/test_script.sh
after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
  webhooks:
      #urls:
      #- https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
