language: python
python:
    - "2.6_with_system_site_packages"
    - "2.7_with_system_site_packages"

# command to install dependencies
install: 
    - "pip install -r requirements.txt"
# # command to run tests
before_script: "sudo aptitude -y -q install ffmpeg mediainfo"
script: nosetests2 -v skvideo
