language: python
python:
    - "2.6"
    - "2.7"

# command to install dependencies
install: 
    - pip install numpy
    - pip install scipy
# # command to run tests
before_script: "sudo aptitude -y -q install ffmpeg mediainfo"
script: nosetests
