# make it explicit that we favor the new container-based travis workers
language: python

os:
  - linux
    #  - osx

python:
  - 2.7
  - 2.6
  - 3.3

notifications:
  email: true

# Pre-install packages for the ubuntu distribution
cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
addons:
  apt:
    packages:
      - libatlas-dev
      - ffmpeg # wrong version (libav), installed only for dependencies that come with it
      - mediainfo

env:
  global:
    - COVERAGE="true"
  matrix:
    # Primary targets.
    - FFMPEG=2.1 LIBAV=10.7
    - FFMPEG=2.8 LIBAV=11.4
    - FFMPEG=snapshot LIBAV=gitrepo

before_install: 
  - source scripts/before_install.sh

install: 
  - source scripts/install.sh

script: 
  - bash scripts/script.sh

after_success:
  # Ignore coveralls failures as the coveralls server is not very reliable
  # but we don't want travis to report a failure in the github UI just
  # because the coverage report failed to be published.
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
  webhooks:
      #urls:
      #- https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
