# make it explicit that we favor the new container-based travis workers
sudo: required

notifications:
  email: true

matrix:
    global:
        COVERAGE="true"
    include:
        - os: linux
          python: "2.7"
          language: python
          env: FFMPEG=snapshot LIBAV=gitrepo
        - os: osx
          python: "2.6"
          env: TRAVIS_PYTHON_VERSION=2.6 FFMPEG=2.1 LIBAV=10.7
        - os: osx
          python: "2.6"
          env: TRAVIS_PYTHON_VERSION=2.6 FFMPEG=2.8 LIBAV=11.4
        - os: osx
          python: "2.6"
          env: TRAVIS_PYTHON_VERSION=2.6 FFMPEG=snapshot LIBAV=gitrepo
        - os: osx
          python: "2.7"
          env: TRAVIS_PYTHON_VERSION=2.7 FFMPEG=2.1 LIBAV=10.7
        - os: osx
          python: "2.7"
          env: TRAVIS_PYTHON_VERSION=2.7 FFMPEG=2.8 LIBAV=11.4
        - os: osx
          python: "2.7"
          env: TRAVIS_PYTHON_VERSION=2.7 FFMPEG=snapshot LIBAV=gitrepo

before_install: 
  - source scripts/before_install.sh

install: 
  - source scripts/install.sh

script: 
  - bash scripts/script.sh

after_success:
  # Ignore coveralls failures as the coveralls server is not very reliable
  # but we don't want travis to report a failure in the github UI just
  # because the coverage report failed to be published.
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
  webhooks:
      #urls:
      #- https://webhooks.gitter.im/e/4ffabb4df010b70cd624
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
